# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0fdac5e0aa21b5e64169511534320cb764f4da0d1d9857700f2051554aeb8ff25e0d3a831864bb5e46b25c5f79e0af82e63b47f39f2383da2ab5ad54ed4d659

test:
  secret_key_base: c9b6e7d5993ad7c21a6cdb86f9efc669778a540bd93c95dddd30c428438d9548602a0dd382b9ecc902bcaf81c9285f761b4daa163049ac9d8858115d747e0dd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
